/* Build step: compile the reel JSX sources into a single plain-JS bundle
   so the browser needs no Babel at runtime.
   Usage: node reel/build.js /path/to/babel.min.js  (defaults to /tmp/babel.min.js)
   Output: reel/reel.bundle.js */
const fs = require('fs');
const path = require('path');

const babelPath = process.argv[2] || '/tmp/babel.min.js';
const Babel = require(babelPath);

const dir = __dirname;
const sources = ['animations.jsx', 'scenes.jsx', 'app.jsx'];

let out = '/* Auto-generated by reel/build.js — do not edit directly. */\n';
for (const f of sources) {
  const code = fs.readFileSync(path.join(dir, f), 'utf8');
  const res = Babel.transform(code, {
    presets: ['react'],
    filename: f,
    compact: false,
  });
  out += '\n/* ===== ' + f + ' ===== */\n' + res.code + '\n';
}

fs.writeFileSync(path.join(dir, 'reel.bundle.js'), out);
console.log('Wrote reel/reel.bundle.js (' + out.length + ' bytes)');
